# Generated by Django 5.2.5 on 2025-08-31 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_console_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='console',
            name='created_at',
        ),
    ]
